services:
  aptabase_db:
    image: "postgres:15-alpine"
    restart: always
    environment:
      - "POSTGRES_USER=${SERVICE_USER_POSTGRES}"
      - "POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}"
      - POSTGRES_DB=aptabase
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "--username=${SERVICE_USER_POSTGRES}"
        - "--host=127.0.0.1"
        - "--port=5432"
        - "--dbname=aptabase"
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
  aptabase_events_db:
    image: "clickhouse/clickhouse-server:23.8.4.69-alpine"
    restart: always
    environment:
      - "CLICKHOUSE_USER=${SERVICE_USER_CLICKHOUSE}"
      - "CLICKHOUSE_PASSWORD=${SERVICE_PASSWORD_CLICKHOUSE}"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test:
        - CMD
        - wget
        - "--no-verbose"
        - "--tries=1"
        - "--spider"
        - "http://127.0.0.1:8123/ping"
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 15s
  aptabase:
    image: "ghcr.io/aptabase/aptabase:main"
    restart: always
    depends_on:
      aptabase_db:
        condition: service_healthy
      aptabase_events_db:
        condition: service_healthy
    environment:
      - SERVICE_FQDN_APTABASE_8080
      - "BASE_URL=${SERVICE_FQDN_APTABASE}"
      - "AUTH_SECRET=${SERVICE_BASE64_APTABASE}"
      - "DATABASE_URL=Server=aptabase_db;Port=5432;User Id=${SERVICE_USER_POSTGRES};Password=${SERVICE_PASSWORD_POSTGRES};Database=aptabase"
      - "CLICKHOUSE_URL=Host=aptabase_events_db;Port=8123;Username=${SERVICE_USER_CLICKHOUSE};Password=${SERVICE_PASSWORD_CLICKHOUSE}"
